[project]
name = "piratepepe"
version = "0.1.1"
description = "Download the official Matt Furie PEPE NFTs"
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "Kieran Gee", email = "kieran.lost.the.game@gmail.com" }]
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.5",
    "colorama>=0.4.6",
    "python-magic>=0.4.27",
    "tqdm>=4.67.1",
    "pydantic>=2.12.5",
    "typed-ffmpeg>=3.8.1",
    "rich>=14.2.0",
]

[project.optional-dependencies]
dev = ["ruff", "mypy", "types-requests", "types-colorama", "types-tqdm"]

[build-system]
requires = ["uv_build>=0.9.15,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""

[project.scripts]
piratepepe = "piratepepe.__main__:main"

[tool.ruff]
cache-dir = "~/.cache/ruff"
target-version = "py311"
line-length = 120

[tool.ruff.lint]
extend-fixable = ["B", "I001"]
select = ["ALL"] # include all the rules, including new ones
ignore = [
    # Modules
    "DJ", # Django

    # Specific rules
    "T201",   # Print is fine at this scale
    "TD002",  # Verbose TODO, only I work on this project
    "TD002",  # Verbose TODO, only I work on this project
    "TD003",  # Verbose TODO, only I work on this project
    "ISC001", # KG conflict in the formatter
    "COM812", # KG conflict in the formatter
    "S311",   # KG No crypto done here
]

[tool.ruff.lint.flake8-pytest-style]
fixture-parentheses = false

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = 40

[tool.mypy]
files = ["piratepepe"]
namespace_packages = true
explicit_package_bases = true
show_error_codes = true
strict = true
enable_error_code = [
    "ignore-without-code",
    "redundant-expr",
    "truthy-bool",
    "type-arg",
]
