---
name: Ruff

on: [push, pull_request]

jobs:
  check_py:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/ruff-action@v3
        with:
          version-file: pyproject.toml
