---
name: Ruff

on: [push, pull_request]

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ruff
        run: pipx install ruff

      - name: Add ~/.local/.bin to path for pipx packages
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.9"

      - name: Run ruff
        run: ruff check .
